-- 데모용 테넌트와 사용자를 넣는다.
--
--   psql "$DATABASE_URL" -v key="$DB_ENCRYPTION_KEY" -v cipher=aes256 -f scripts/seed-demo.sql
--
-- 마이그레이션이 아니라 스크립트로 둔 이유는 이것이 데모 데이터이기 때문이다. 마이그레이션에
-- 넣으면 이 데이터를 원하지 않는 환경에도 따라 들어가고, 나중에 빼려면 지우는 마이그레이션을
-- 또 만들어야 한다. 필요한 환경에서 필요할 때 실행한다.
--
-- 왜 필요한가. 이 프로젝트에는 토큰 발급이 없고, 프론트가 X-User-Id 헤더로 신원을 보낸다
-- (web 저장소 src/data/demoUsers.ts). 그 파일이 사용자 1·2·3 이 서버에 있다고 전제하므로,
-- 이 스크립트를 돌리지 않으면 화면은 떠도 모든 요청이 401 로 실패한다.
--
-- 여러 번 실행해도 안전하다. 이미 있으면 넘어간다.

\set ON_ERROR_STOP on

-- app_user.name 은 bytea 이고 app_encrypt 로만 넣을 수 있다. 그 함수가 세션 설정에서
-- 키와 알고리즘을 읽으므로 INSERT 전에 넣어 준다.
--
-- 알고리즘은 환경에 따라 다르다. dev 와 배포는 ARIA-256(Tmax OpenCrypto)을 쓰고, 로컬
-- PostgreSQL 의 pgcrypto 에는 ARIA 가 없어 AES-256 을 쓴다. 호출하는 쪽이 -v cipher=... 로
-- 정하고, 주지 않으면 운영 기본값인 aria256 을 쓴다.
SELECT set_config('app.encryption_key', :'key', false);
SELECT set_config('app.encryption_cipher', coalesce(nullif(:'cipher', ''), 'aria256'), false);

BEGIN;

-- 테넌트 3개. 테넌트 간 격리와 테넌트 단위 권한 부여를 보이려면 최소 2개가 필요하고,
-- demoUsers.ts 가 3개를 전제한다.
INSERT INTO tenant (id, name) VALUES
    (1, '테넌트 A'),
    (2, '테넌트 B'),
    (3, '테넌트 C')
ON CONFLICT (id) DO NOTHING;

-- 사용자 3명. id 는 demoUsers.ts 의 값과 일치해야 한다. 한 명씩 다른 테넌트에 두어
-- 한쪽에서 올린 문서가 다른 쪽 검색 결과에 나오지 않는 것을 보일 수 있게 한다.
INSERT INTO app_user (id, tenant_id, email, name) VALUES
    (1, 1, 'user-a@example.com', app_encrypt('사용자 A'::bytea)),
    (2, 2, 'user-b@example.com', app_encrypt('사용자 B'::bytea)),
    (3, 3, 'user-c@example.com', app_encrypt('사용자 C'::bytea))
ON CONFLICT (id) DO NOTHING;

-- id 를 직접 지정해 넣었으므로 시퀀스를 따라 올린다. 이 줄이 없으면 이후 애플리케이션이
-- 만드는 첫 사용자가 id 1 을 받으려 하고 기본키 충돌로 실패한다.
--
-- 컬럼이 GENERATED BY DEFAULT AS IDENTITY 라 명시적 id 삽입은 허용되지만, 시퀀스는
-- 그만큼 따라 오지 않는다. 조용히 어긋난 뒤 나중에 터지는 종류의 문제다.
SELECT setval(pg_get_serial_sequence('tenant', 'id'), (SELECT max(id) FROM tenant), true);
SELECT setval(pg_get_serial_sequence('app_user', 'id'), (SELECT max(id) FROM app_user), true);

COMMIT;

-- 넣은 값을 복호화해서 보여 준다. 여기서 이름이 깨져 나오면 키나 알고리즘이 환경과 맞지 않는
-- 것이므로, 문서를 올리기 전에 알아차릴 수 있다.
SELECT
    u.id,
    u.tenant_id,
    t.name AS tenant_name,
    u.email,
    convert_from(app_decrypt(u.name), 'UTF8') AS user_name
FROM app_user u
JOIN tenant t ON t.id = u.tenant_id
ORDER BY u.id;