-- =============================================================================
-- Tmax OpenSQL 기반 AI 문서 관리 시스템 - 초기 스키마
--
-- 대상: PostgreSQL 17.8 (local) / Tmax OpenSQL v3.0 싱글 인스턴스 (dev)
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 0. 확장
--
-- opencrypto 는 설치하지 않는다. 컬럼 타입(BYTEA)은 확장과 무관하고
-- 암복호화는 쿼리 시점에 일어나므로, 확장이 없는 local 에서도 스키마 생성은 성공한다.
-- -----------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS vector;


-- -----------------------------------------------------------------------------
-- 1. tenant
-- -----------------------------------------------------------------------------

CREATE TABLE tenant (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                        VARCHAR(100) NOT NULL,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- -----------------------------------------------------------------------------
-- 2. app_user
--
-- user 는 PostgreSQL 예약어이므로 app_user 를 사용한다.
-- email 은 UNIQUE 제약과 로그인 조회에 쓰이므로 암호화 대상에서 제외했다.
-- -----------------------------------------------------------------------------

CREATE TABLE app_user (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                   BIGINT NOT NULL,
    email                       VARCHAR(255) NOT NULL,
    name                        BYTEA NOT NULL,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_app_user_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES tenant(id),
    CONSTRAINT uk_app_user_tenant_email
        UNIQUE (tenant_id, email)
);

COMMENT ON COLUMN app_user.name IS '암호화 대상. opencrypto 함수로 암복호화한다.';


-- -----------------------------------------------------------------------------
-- 3. document
-- -----------------------------------------------------------------------------

CREATE TABLE document (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                   BIGINT NOT NULL,
    owner_principal_id          VARCHAR(255) NOT NULL,

    title                       VARCHAR(255) NOT NULL,
    latest_upload_version_no    BIGINT NOT NULL DEFAULT 0,
    latest_embedding_version_no BIGINT NOT NULL DEFAULT 0,
    searchable_version_id       BIGINT,

    deleted_at                  TIMESTAMPTZ,
    purged_at                   TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_document_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES tenant(id),
    CONSTRAINT uk_document_id_tenant
        UNIQUE (id, tenant_id),
    CONSTRAINT ck_document_latest_upload_version_no
        CHECK (latest_upload_version_no >= 0),
    CONSTRAINT ck_document_latest_embedding_version_no
        CHECK (latest_embedding_version_no >= 0),
    CONSTRAINT ck_document_embedding_not_ahead_of_upload
        CHECK (latest_embedding_version_no <= latest_upload_version_no),
    CONSTRAINT ck_document_purged_after_deleted
        CHECK (purged_at IS NULL OR deleted_at IS NOT NULL)
);

COMMENT ON COLUMN document.latest_upload_version_no IS
    '마지막으로 발급된 version_no. 다음 버전 번호 채번에 쓰는 카운터.';
COMMENT ON COLUMN document.latest_embedding_version_no IS
    '임베딩이 완료된 가장 최신 version_no.';
COMMENT ON COLUMN document.searchable_version_id IS
    '검색 대상 document_version 의 PK. latest_embedding_version_no 이하 버전만 지정한다.';
COMMENT ON COLUMN document.purged_at IS
    '물리 정리 완료 시각. 청크 삭제와 원본 삭제가 모두 끝난 뒤 마지막에 기록한다. '
    'NULL 이면 아직 정리되지 않았다는 뜻이므로 스케줄러가 다시 집는다.';


-- -----------------------------------------------------------------------------
-- 4. document_version
-- -----------------------------------------------------------------------------

CREATE TABLE document_version (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id                 BIGINT NOT NULL,
    version_no                  BIGINT NOT NULL,

    source_object_key           VARCHAR(1024) NOT NULL,
    original_filename           BYTEA NOT NULL,
    mime_type                   VARCHAR(100) NOT NULL,
    file_size                   BIGINT NOT NULL,
    content_hash                VARCHAR(128) NOT NULL,

    source_metadata             JSONB,
    extracted_metadata          JSONB,

    chunk_count                 INTEGER,
    indexed_at                  TIMESTAMPTZ,

    created_by_principal_id     VARCHAR(255) NOT NULL,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_document_version_document
        FOREIGN KEY (document_id)
        REFERENCES document(id),
    CONSTRAINT uk_document_version
        UNIQUE (document_id, version_no),
    CONSTRAINT uk_document_version_id_document
        UNIQUE (id, document_id),
    CONSTRAINT ck_document_version_no
        CHECK (version_no > 0),
    CONSTRAINT ck_document_version_file_size
        CHECK (file_size >= 0),
    CONSTRAINT ck_document_version_chunk_count
        CHECK (chunk_count IS NULL OR chunk_count >= 0)
);

COMMENT ON COLUMN document_version.original_filename IS
    '암호화 대상. opencrypto 함수로 암복호화한다.';
COMMENT ON COLUMN document_version.extracted_metadata IS
    '문서 파싱이 아니라 AI 가 생성한 메타데이터.';


-- document.searchable_version_id 의 복합 FK 는 document_version 생성 후 추가한다.
ALTER TABLE document
ADD CONSTRAINT fk_document_searchable_version
    FOREIGN KEY (searchable_version_id, id)
    REFERENCES document_version(id, document_id);


-- -----------------------------------------------------------------------------
-- 5. outbox_event
--
-- DOCUMENT_DELETED 는 문서 단위 이벤트라 document_version_id 가 NULL 이다.
-- status 이하는 릴레이 서버의 폴링 발행용 컬럼이다.
-- -----------------------------------------------------------------------------

CREATE TABLE outbox_event (
    id                          UUID PRIMARY KEY,
    tenant_id                   BIGINT NOT NULL,
    document_id                 BIGINT NOT NULL,
    document_version_id         BIGINT,
    retry_of_event_id           UUID,

    event_type                  VARCHAR(50) NOT NULL,
    event_schema_version        INTEGER NOT NULL DEFAULT 1,
    payload                     JSONB NOT NULL,
    trace_id                    VARCHAR(255),

    status                      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    publish_attempt_count       INTEGER NOT NULL DEFAULT 0,
    next_attempt_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_by                   VARCHAR(255),
    locked_at                   TIMESTAMPTZ,
    published_at                TIMESTAMPTZ,
    last_error_message          TEXT,

    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_outbox_document_tenant
        FOREIGN KEY (document_id, tenant_id)
        REFERENCES document(id, tenant_id),
    CONSTRAINT fk_outbox_document_version
        FOREIGN KEY (document_version_id, document_id)
        REFERENCES document_version(id, document_id),
    CONSTRAINT ck_outbox_schema_version
        CHECK (event_schema_version > 0),
    CONSTRAINT ck_outbox_event_type
        CHECK (event_type IN (
            'INDEXING_REQUESTED',
            'DOCUMENT_DELETED'
        )),
    CONSTRAINT ck_outbox_indexing_request_target
        CHECK (event_type <> 'INDEXING_REQUESTED'
               OR document_version_id IS NOT NULL),
    CONSTRAINT ck_outbox_document_deleted_target
        CHECK (event_type <> 'DOCUMENT_DELETED'
               OR document_version_id IS NULL),
    CONSTRAINT ck_outbox_status
        CHECK (status IN (
            'PENDING',
            'PUBLISHING',
            'PUBLISHED',
            'DEAD'
        )),
    CONSTRAINT ck_outbox_publish_attempt_count
        CHECK (publish_attempt_count >= 0)
);

COMMENT ON COLUMN outbox_event.document_version_id IS
    'INDEXING_REQUESTED 는 버전 단위라 값을 가지고, DOCUMENT_DELETED 는 문서 단위라 NULL 이다.';
COMMENT ON COLUMN outbox_event.next_attempt_at IS
    '이 시각부터 발행 대상이 된다. 최초 행도 값을 가진다.';
COMMENT ON COLUMN outbox_event.retry_of_event_id IS
    '재발행 건이 가리키는 원본 이벤트. 신규 업로드 건은 NULL 이다.';
COMMENT ON COLUMN outbox_event.locked_by IS
    '이 행을 집은 릴레이 인스턴스. 릴레이를 다중화하면 한 행을 둘이 집는 것을 막는다.';
COMMENT ON COLUMN outbox_event.locked_at IS
    'PUBLISHING 으로 바뀐 시각. 발행 중 죽은 행을 회수하는 기준이라 릴레이가 한 대여도 필요하다.';
COMMENT ON COLUMN outbox_event.trace_id IS
    '트리거는 애플리케이션 트레이스 컨텍스트에 접근할 수 없으므로, '
    '트랜잭션에서 SET LOCAL app.trace_id 로 넘긴 값을 읽는다.';


-- -----------------------------------------------------------------------------
-- 6. indexing_job
-- -----------------------------------------------------------------------------

CREATE TABLE indexing_job (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_event_id             UUID NOT NULL,
    document_id                 BIGINT NOT NULL,
    document_version_id         BIGINT NOT NULL,

    status                      VARCHAR(30) NOT NULL,
    attempt_count               INTEGER NOT NULL DEFAULT 0,
    next_retry_at               TIMESTAMPTZ,

    worker_id                   VARCHAR(255),
    last_error_code             VARCHAR(100),
    last_error_message          TEXT,
    trace_id                    VARCHAR(255),

    started_at                  TIMESTAMPTZ,
    completed_at                TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_indexing_job_source_event
        UNIQUE (source_event_id),
    CONSTRAINT fk_indexing_job_document_version
        FOREIGN KEY (document_version_id, document_id)
        REFERENCES document_version(id, document_id),
    CONSTRAINT ck_indexing_job_status
        CHECK (status IN (
            'PENDING',
            'PROCESSING',
            'RETRY_WAIT',
            'COMPLETED',
            'FAILED'
        )),
    CONSTRAINT ck_indexing_job_attempt_count
        CHECK (attempt_count >= 0)
);

-- source_event_id 에는 의도적으로 FK 를 걸지 않는다.
-- Outbox 행은 발행 후 정리할 수 있어야 하지만 Job 의 이력은 더 오래 남긴다.


-- -----------------------------------------------------------------------------
-- 7. document_chunk
--
-- VECTOR(1536) 의 차원은 잠정값이다. 임베딩 모델이 확정되면 변경한다.
-- tenant_id 는 document 에서 내려온 반정규화 컬럼이다. 검색 필터와 벡터 컬럼을
-- 같은 테이블에 두기 위한 것이라 값의 일치는 복합 FK 로 강제한다.
-- -----------------------------------------------------------------------------

CREATE TABLE document_chunk (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                   BIGINT NOT NULL,
    document_version_id         BIGINT NOT NULL,
    document_id                 BIGINT NOT NULL,
    chunk_no                    INTEGER NOT NULL,

    content                     TEXT NOT NULL,
    content_hash                VARCHAR(128) NOT NULL,
    token_count                 INTEGER,

    page_from                   INTEGER,
    page_to                     INTEGER,
    section_path                VARCHAR(1024),
    metadata                    JSONB,

    embedding                   VECTOR(1536) NOT NULL,
    embedded_at                 TIMESTAMPTZ NOT NULL,

    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_document_chunk
        UNIQUE (document_version_id, chunk_no),
    CONSTRAINT fk_document_chunk_version_document
        FOREIGN KEY (document_version_id, document_id)
        REFERENCES document_version(id, document_id),
    CONSTRAINT fk_document_chunk_document_tenant
        FOREIGN KEY (document_id, tenant_id)
        REFERENCES document(id, tenant_id),
    CONSTRAINT ck_document_chunk_no
        CHECK (chunk_no >= 0),
    CONSTRAINT ck_document_chunk_token_count
        CHECK (token_count IS NULL OR token_count >= 0),
    CONSTRAINT ck_document_chunk_page_range
        CHECK (
            page_from IS NULL
            OR page_to IS NULL
            OR page_from <= page_to
        )
);


-- -----------------------------------------------------------------------------
-- 8. document_access_scope
-- -----------------------------------------------------------------------------

CREATE TABLE document_access_scope (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                   BIGINT NOT NULL,
    document_id                 BIGINT NOT NULL,

    principal_type              VARCHAR(30) NOT NULL,
    principal_id                VARCHAR(255) NOT NULL,
    permission                  VARCHAR(20) NOT NULL DEFAULT 'READ',

    granted_by_principal_id     VARCHAR(255) NOT NULL,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_access_scope_document_tenant
        FOREIGN KEY (document_id, tenant_id)
        REFERENCES document(id, tenant_id),
    CONSTRAINT uk_document_access_scope
        UNIQUE (document_id, principal_type, principal_id),
    CONSTRAINT ck_access_scope_principal_type
        CHECK (principal_type IN (
            'USER',
            'TENANT'
        )),
    CONSTRAINT ck_access_scope_permission
        CHECK (permission IN ('READ', 'WRITE', 'ADMIN'))
);


-- -----------------------------------------------------------------------------
-- 9. 인덱스
--
-- 벡터 인덱스(HNSW)는 벡터 검색 담당이 별도 마이그레이션 파일로 관리한다.
-- -----------------------------------------------------------------------------

CREATE INDEX idx_document_tenant_active
    ON document (tenant_id, id)
    WHERE deleted_at IS NULL;

-- 삭제 정리 스케줄러의 스캔 대상.
CREATE INDEX idx_document_pending_purge
    ON document (deleted_at)
    WHERE deleted_at IS NOT NULL AND purged_at IS NULL;

CREATE INDEX idx_document_version_document
    ON document_version (document_id, version_no DESC);

-- 릴레이 폴링 전용. 발행이 끝난 행은 빠지므로 Outbox 가 쌓여도 크기가 유지된다.
CREATE INDEX idx_outbox_pending
    ON outbox_event (next_attempt_at, id)
    WHERE status = 'PENDING';

-- PUBLISHING 상태로 멈춘 좀비 행 회수
CREATE INDEX idx_outbox_stuck
    ON outbox_event (locked_at)
    WHERE status = 'PUBLISHING';

-- 한 문서 버전에 진행 중인 Job 은 하나만 존재하도록 강제한다.
CREATE UNIQUE INDEX uq_indexing_job_active_version
    ON indexing_job (document_version_id)
    WHERE status IN ('PENDING', 'PROCESSING', 'RETRY_WAIT');

CREATE INDEX idx_indexing_job_retry
    ON indexing_job (status, next_retry_at)
    WHERE status IN ('PENDING', 'RETRY_WAIT');

-- 한 문서 버전의 인덱싱 이력 조회
CREATE INDEX idx_indexing_job_version
    ON indexing_job (document_version_id, created_at DESC);

CREATE INDEX idx_chunk_document_version
    ON document_chunk (document_version_id, chunk_no);

-- 하이브리드 검색의 키워드 쪽. 색인 구성(simple)은 검색 튜닝 결과에 따라
-- 별도 마이그레이션으로 바꿀 수 있다.
CREATE INDEX idx_document_chunk_content_tsv
    ON document_chunk USING GIN (to_tsvector('simple', content));

CREATE INDEX idx_access_scope_principal
    ON document_access_scope (
        tenant_id,
        principal_type,
        principal_id,
        document_id
    );


-- -----------------------------------------------------------------------------
-- 10. Outbox 트리거
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION fn_outbox_indexing_requested()
RETURNS TRIGGER AS $$
DECLARE
    v_tenant_id BIGINT;
    v_event_id  UUID;
BEGIN
    SELECT tenant_id
      INTO v_tenant_id
      FROM document
     WHERE id = NEW.document_id;

    v_event_id := gen_random_uuid();

    INSERT INTO outbox_event (
        id,
        tenant_id,
        document_id,
        document_version_id,
        event_type,
        event_schema_version,
        payload,
        trace_id
    )
    VALUES (
        v_event_id,
        v_tenant_id,
        NEW.document_id,
        NEW.id,
        'INDEXING_REQUESTED',
        1,
        jsonb_build_object(
            'tenantId',        v_tenant_id,
            'versionNo',       NEW.version_no,
            'sourceObjectKey', NEW.source_object_key,
            'mimeType',        NEW.mime_type,
            'fileSize',        NEW.file_size,
            'contentHash',     NEW.content_hash,
            'occurredAt',      to_char(
                                   CURRENT_TIMESTAMP AT TIME ZONE 'UTC',
                                   'YYYY-MM-DD"T"HH24:MI:SS"Z"'
                               )
        ),
        current_setting('app.trace_id', true)
    );

    -- 알림은 유실될 수 있으므로 릴레이는 폴링도 함께 수행해야 한다.
    -- pg_notify 는 8000바이트 제한이 있어 ID 만 보내고 릴레이가 다시 조회한다.
    PERFORM pg_notify('outbox_event', v_event_id::text);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER trg_document_version_outbox
    AFTER INSERT ON document_version
    FOR EACH ROW
    EXECUTE FUNCTION fn_outbox_indexing_requested();


-- 삭제는 deleted_at 을 채우는 소프트 삭제이므로 UPDATE 를 감시한다.
-- 청크 정리는 워커가 이 이벤트를 받아서 수행한다.
CREATE OR REPLACE FUNCTION fn_outbox_document_deleted()
RETURNS TRIGGER AS $$
DECLARE
    v_event_id UUID;
BEGIN
    v_event_id := gen_random_uuid();

    INSERT INTO outbox_event (
        id,
        tenant_id,
        document_id,
        document_version_id,
        event_type,
        event_schema_version,
        payload,
        trace_id
    )
    VALUES (
        v_event_id,
        NEW.tenant_id,
        NEW.id,
        NULL,
        'DOCUMENT_DELETED',
        1,
        jsonb_build_object(
            'tenantId',   NEW.tenant_id,
            'deletedAt',  to_char(
                              NEW.deleted_at AT TIME ZONE 'UTC',
                              'YYYY-MM-DD"T"HH24:MI:SS"Z"'
                          ),
            'occurredAt', to_char(
                              CURRENT_TIMESTAMP AT TIME ZONE 'UTC',
                              'YYYY-MM-DD"T"HH24:MI:SS"Z"'
                          )
        ),
        current_setting('app.trace_id', true)
    );

    PERFORM pg_notify('outbox_event', v_event_id::text);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- WHEN 절이 이벤트를 삭제 시점 한 번으로 제한한다.
-- deleted_at 이 이미 채워진 행을 다시 UPDATE 해도 이벤트가 늘지 않는다.
CREATE TRIGGER trg_document_deleted_outbox
    AFTER UPDATE ON document
    FOR EACH ROW
    WHEN (OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL)
    EXECUTE FUNCTION fn_outbox_document_deleted();
